/**
 * UI strings for the `play` area: the three-column chat where the narrator writes.
 *
 * Split by area so two people can work on different screens without touching
 * the same file. Every area exports the same five languages, because a key that
 * exists only in English is a key nobody notices is missing.
 *
 * Plain object literals, no `as Record<string, string>`: the annotation would
 * widen the key set to `string` and the four translations below would stop being
 * checked against English, which is the whole reason this file has five copies.
 *
 * Dynamic values are `{{placeholders}}` and not concatenation, so each language
 * puts them where its grammar wants them. Where a page needs a sentence with two
 * numbers in it, they are named (`{{with}}` / `{{without}}`) rather than numbered.
 */
export const playEn = {
  "play.tabs.overview": "Overview",
  "play.tabs.history": "History",
  "play.tabs.adaptation": "Adaptation",

  "play.turn.narrator": "narrator",
  "play.turn.typing": "the narrator is writing",
  "play.turn.disclaimer": "Everything here is generated by AI and is purely fictional.",
  "play.turn.failedOne": "A turn didn't go through.",
  "play.turn.failedMany": "{{count}} turns didn't go through.",
  "play.turn.failedWhy":
    "They are here because what you wrote must not be lost, and the history alone doesn't tell what went wrong.",

  "play.action.send": "✨ Send",
  "play.action.continue": "✨ Continue",
  "play.action.retry": "↻ Retry",
  "play.action.delete": "⌫ Delete",
  "play.action.reset": "⟲ Start over",
  "play.action.discard": "discard",

  "play.composer.placeholder": "Speak, describe what you do or what happens next.",
  "play.composer.writing": "writing…",
  "play.composer.locationUnset": "Undeclared place",
  "play.composer.locationTitle":
    "It helps the narrator know who is present and which canon applies here. It doesn't write it by itself: a place becomes canon only if you declare it.",
  "play.composer.continueTitle":
    "The narrator goes on. It isn't your action, so it doesn't end up in the chat.",
  "play.composer.retryIdleTitle": "Active only if the last prompt failed",
  "play.composer.retryTitle": "Retries the last prompt",
  "play.composer.redoTitle":
    "The narrator tells the last scene again, differently. Same circumstances, same canon, different outcome.",
  "play.composer.deleteTitle": "Deletes a single message: only the last one",
  "play.composer.resetTitle":
    "Opens a new conversation. Canon, characters and chapters stay; the chat starts again from the prologue.",

  "play.settings.title": "Settings",
  "play.settings.freeBadge": "Free",
  "play.settings.writingHint": "The narrator is writing: the new model applies from the next turn.",
  "play.settings.canonSummary": "Canon in the context",
  "play.settings.arcMemory": "Arc memory",
  "play.settings.chat": "Chat settings",

  "play.context.estimated": "Estimated context",
  "play.context.limit": "limit {{limit}}",
  "play.context.tokens": "{{count}} tokens",
  "play.context.chapterAt": "chapter at {{limit}}",
  "play.context.canonEntries": "{{entries}} entries · {{tokens}} tokens",
  "play.context.canonOverBudget":
    "the mandatory tiers exceed the budget: a model with more context is needed",
  "play.context.arcTokens": "{{with}} tokens instead of {{without}}",
  "play.context.arcSaved": " · saving {{percent}}%",
  "play.context.placeFree":
    "The place is the one you say in the text. Choosing one here tells the narrator who is present and which canon applies, but it doesn't make it canon: you decide that.",
  "play.context.placeChosen": "The narrator will believe you are at {{place}}.",
  "play.context.placeUnknown": "that place",
  "play.context.newNames":
    "The narrator cited names the canon doesn't contain. Nothing enters the database during play: you decide.",

  "play.state.worldFallback": "The world",
  "play.state.emptyHint":
    "Write what you want to happen. The narrator answers inside the world, and will never do something the canon doesn't allow.",
  "play.state.noDescription": "No description.",
  "play.state.noChapter": "none yet",
  "play.state.noTier": "no tier",

  /*
   * The start selector.
   *
   * It says nothing about games it does not offer. A campaign that has not begun
   * is a few words and a list of names: the player picks where to enter the world,
   * and the narrator opens on that. The line about "you decide who you are" is
   * there because the starts are openings to somebody else's story, and a player
   * who assumes they are about to play the protagonist is in for a surprise on
   * their first turn.
   */
  "play.start.title": "How does your story begin?",
  "play.start.hint": "Pick where to enter this world. You decide who you are.",
  "play.start.choose": "Begin here",
  "play.start.chosen": "Selected",
  "play.start.change": "Change the start",
  "play.start.loreOnly": "Lore only, not playable",
  "play.start.selected": "The campaign begins here.",
  "play.start.titleAttribute": "{{name}}: {{summary}}",
  "play.start.aria.group": "Campaign starts",
  "play.start.aria.open": "Choose how this campaign begins",
  "play.start.aria.close": "Close the start selector",

  "play.error.loadTitle": "I can't load this campaign.",
  "play.error.loadFailed": "I couldn't load this campaign.",
  "play.error.loadPartial": "I couldn't load everything.",
  "play.error.stale":
    "The narrator didn't finish the turn: the backend stopped or restarted while it was writing, and the reply never arrived.",
  "play.error.turnFailed": "The turn failed.",
  "play.error.turnUnfinished": "The turn was left half done and nobody is writing it.",
  "play.error.turnNotFinished": "The narrator didn't finish this turn.",
  "play.error.neverReached": "It never reached the narrator.",

  "play.confirm.reset":
    "Start the conversation over? The world prologue stays, the messages go away and the cast of this playthrough is deleted. Canon, eras, Bible, arcs and chapters are untouched.",
  "play.confirm.removeCharacter": "Remove {{name}} from the world?",

  "play.adapt.castTitle": "Cast characters",
  "play.adapt.castEmpty": "No canon character. They appear when you promote them.",
  "play.adapt.placesTitle": "Places",
  "play.adapt.placesEmpty": "No canon place.",
  "play.adapt.remove": "remove",
  "play.adapt.removeLabel": "Remove {{name}}",
  "play.adapt.removeTitle": "Remove from the world",

  "play.history.chapters": "Chapters",
  "play.history.openNotebook": "open the world notebook",

  "play.locale.chip": "locale",

  "play.aria.backHome": "Back to the home",
};

/** Italian: the text this area was born with, cleaned up and nothing else. */
export const playIt = {
  "play.tabs.overview": "Panoramica",
  "play.tabs.history": "Cronologia",
  "play.tabs.adaptation": "Adattamento",

  "play.turn.narrator": "narratore",
  "play.turn.typing": "il narratore sta scrivendo",
  "play.turn.disclaimer": "Tutto il contenuto qui è generato dall'IA ed è puramente fittizio.",
  "play.turn.failedOne": "Un turno non è andato a buon fine.",
  "play.turn.failedMany": "{{count}} turni non sono andati a buon fine.",
  "play.turn.failedWhy":
    "Sono qui perché quello che hai scritto non va perso, e la cronologia da sola non racconta quello che è andato storto.",

  "play.action.send": "✨ Invia",
  "play.action.continue": "✨ Continua",
  "play.action.retry": "↻ Riprova",
  "play.action.delete": "⌫ Cancella",
  "play.action.reset": "⟲ Ricomincia",
  "play.action.discard": "butta",

  "play.composer.placeholder": "Parla, descrivi cosa fai o cosa succede dopo.",
  "play.composer.writing": "scrive…",
  "play.composer.locationUnset": "Luogo non dichiarato",
  "play.composer.locationTitle":
    "Serve al narratore per sapere chi è presente e quale canone vale qui. Non lo scrive da solo: un luogo diventa canonico solo se lo dichiari tu.",
  "play.composer.continueTitle":
    "Il narratore prosegue. Non è un'azione tua, quindi non finisce in chat.",
  "play.composer.retryIdleTitle": "Attivo solo se l'ultimo prompt è fallito",
  "play.composer.retryTitle": "Ritenta l'ultimo prompt",
  "play.composer.redoTitle":
    "Il narratore rifà l'ultima scena, cambiando come è andata. Stesse circostanze, stesso canone, esito diverso.",
  "play.composer.deleteTitle": "Cancella un solo messaggio: solo l'ultimo",
  "play.composer.resetTitle":
    "Apre una conversazione nuova. Canone, personaggi e capitoli restano; la chat ricomincia dal prologo.",

  "play.settings.title": "Impostazioni",
  "play.settings.freeBadge": "Gratuito",
  "play.settings.writingHint":
    "Il narratore sta scrivendo: il modello nuovo vale dal prossimo turno.",
  "play.settings.canonSummary": "Canone nel contesto",
  "play.settings.arcMemory": "Memoria degli archi",
  "play.settings.chat": "Impostazioni chat",

  "play.context.estimated": "Contesto stimato",
  "play.context.limit": "limite {{limit}}",
  "play.context.tokens": "{{count}} token",
  "play.context.chapterAt": "capitolo a {{limit}}",
  "play.context.canonEntries": "{{entries}} voci · {{tokens}} token",
  "play.context.canonOverBudget":
    "i tier obbligatori superano il budget: serve un modello con più contesto",
  "play.context.arcTokens": "{{with}} token invece di {{without}}",
  "play.context.arcSaved": " · risparmio {{percent}}%",
  "play.context.placeFree":
    "Il luogo è quello che dici tu nel testo. Scegliendone uno qui, il narratore sa chi è presente e quale canone vale, ma non lo rende canonico: quello decidi tu.",
  "play.context.placeChosen": "Il narratore crederà che tu sia a {{place}}.",
  "play.context.placeUnknown": "quel luogo",
  "play.context.newNames":
    "Il narratore ha citato nomi che il canone non contiene. In partita non entra niente nel database: decidi tu.",

  "play.state.worldFallback": "Il mondo",
  "play.state.emptyHint":
    "Scrivi quello che vuoi che succeda. Il narratore risponde dentro il mondo, e non farà mai qualcosa che il canone non consente.",
  "play.state.noDescription": "Nessuna descrizione.",
  "play.state.noChapter": "nessuno ancora",
  "play.state.noTier": "nessun tier",

  "play.start.title": "Come comincia la tua storia?",
  "play.start.hint": "Scegli da dove entrare in questo mondo. Decidi chi sei.",
  "play.start.choose": "Comincia qui",
  "play.start.chosen": "Selezionato",
  "play.start.change": "Cambia inizio",
  "play.start.loreOnly": "Solo lore, non giocabile",
  "play.start.selected": "La campagna comincia qui.",
  "play.start.titleAttribute": "{{name}}: {{summary}}",
  "play.start.aria.group": "Inizi della campagna",
  "play.start.aria.open": "Scegli come comincia questa campagna",
  "play.start.aria.close": "Chiudi il selettore degli inizi",

  "play.error.loadTitle": "Non riesco a caricare questa campagna.",
  "play.error.loadFailed": "Non sono riuscito a caricare questa campagna.",
  "play.error.loadPartial": "Non sono riuscito a caricare tutto.",
  "play.error.stale":
    "Il narratore non ha finito il turno: il backend si è fermato o riavviato mentre scriveva, e la risposta non è mai arrivata.",
  "play.error.turnFailed": "Il turno è fallito.",
  "play.error.turnUnfinished": "Il turno è rimasto a metà e nessuno lo sta scrivendo.",
  "play.error.turnNotFinished": "Il narratore non ha finito questo turno.",
  "play.error.neverReached": "Non è mai arrivato al narratore.",

  "play.confirm.reset":
    "Ricomincia la conversazione? Il prologo del mondo resta, i messaggi vanno via e il cast di questa partita viene cancellato. Canone, epoche, Bible, archi e capitoli non si toccano.",
  "play.confirm.removeCharacter": "Togliere {{name}} dal mondo?",

  "play.adapt.castTitle": "Personaggi del cast",
  "play.adapt.castEmpty": "Nessun personaggio canonico. Compaiono quando li promuovi tu.",
  "play.adapt.placesTitle": "Luoghi",
  "play.adapt.placesEmpty": "Nessun luogo canonico.",
  "play.adapt.remove": "togli",
  "play.adapt.removeLabel": "Togliere {{name}}",
  "play.adapt.removeTitle": "Togliere dal mondo",

  "play.history.chapters": "Capitoli",
  "play.history.openNotebook": "apri il quaderno del mondo",

  "play.locale.chip": "locale",

  "play.aria.backHome": "Torna alla home",
};

export const playEs = {
  "play.tabs.overview": "Panorámica",
  "play.tabs.history": "Cronología",
  "play.tabs.adaptation": "Adaptación",

  "play.turn.narrator": "narrador",
  "play.turn.typing": "el narrador está escribiendo",
  "play.turn.disclaimer": "Todo el contenido de aquí lo genera una IA y es puramente ficticio.",
  "play.turn.failedOne": "Un turno no ha salido bien.",
  "play.turn.failedMany": "{{count}} turnos no han salido bien.",
  "play.turn.failedWhy":
    "Están aquí porque lo que escribiste no debe perderse, y el historial por sí solo no cuenta lo que salió mal.",

  "play.action.send": "✨ Enviar",
  "play.action.continue": "✨ Continuar",
  "play.action.retry": "↻ Reintentar",
  "play.action.delete": "⌫ Borrar",
  "play.action.reset": "⟲ Empezar de nuevo",
  "play.action.discard": "descarta",

  "play.composer.placeholder": "Habla, describe qué haces o qué ocurre después.",
  "play.composer.writing": "escribiendo…",
  "play.composer.locationUnset": "Lugar sin declarar",
  "play.composer.locationTitle":
    "Ayuda al narrador a saber quién está presente y qué canon vigente hay aquí. No lo escribe por sí solo: un lugar solo se vuelve canon si tú lo declaras.",
  "play.composer.continueTitle":
    "El narrador continúa. No es una acción tuya, así que no acaba en el chat.",
  "play.composer.retryIdleTitle": "Activo solo si la última instrucción falló",
  "play.composer.retryTitle": "Reintenta la última instrucción",
  "play.composer.redoTitle":
    "El narrador cuenta de nuevo la última escena, de otra manera. Mismas circunstancias, mismo canon, resultado distinto.",
  "play.composer.deleteTitle": "Borra un solo mensaje: solo el último",
  "play.composer.resetTitle":
    "Abre una conversación nueva. El canon, los personajes y los capítulos se quedan; el chat vuelve a empezar por el prólogo.",

  "play.settings.title": "Ajustes",
  "play.settings.freeBadge": "Gratis",
  "play.settings.writingHint":
    "El narrador está escribiendo: el modelo nuevo válida a partir del próximo turno.",
  "play.settings.canonSummary": "Canon en el contexto",
  "play.settings.arcMemory": "Memoria de los arcos",
  "play.settings.chat": "Ajustes del chat",

  "play.context.estimated": "Contexto estimado",
  "play.context.limit": "límite {{limit}}",
  "play.context.tokens": "{{count}} tokens",
  "play.context.chapterAt": "capítulo en {{limit}}",
  "play.context.canonEntries": "{{entries}} entradas · {{tokens}} tokens",
  "play.context.canonOverBudget":
    "los niveles obligatorios superan el presupuesto: hace falta un modelo con más contexto",
  "play.context.arcTokens": "{{with}} tokens en lugar de {{without}}",
  "play.context.arcSaved": " · ahorro {{percent}}%",
  "play.context.placeFree":
    "El lugar es el que digas en el texto. Al elegir uno aquí, el narrador sabe quién está presente y qué canon vigente hay, pero no lo vuelve canon: eso lo decides tú.",
  "play.context.placeChosen": "El narrador creerá que estás en {{place}}.",
  "play.context.placeUnknown": "ese lugar",
  "play.context.newNames":
    "El narrador ha citado nombres que el canon no contiene. Durante la partida no entra nada en la base de datos: lo decides tú.",

  "play.state.worldFallback": "El mundo",
  "play.state.emptyHint":
    "Escribe lo que quieres que ocurra. El narrador responde dentro del mundo y nunca hará algo que el canon no permita.",
  "play.state.noDescription": "Sin descripción.",
  "play.state.noChapter": "ninguno todavía",
  "play.state.noTier": "ningún nivel",

  "play.start.title": "¿Cómo empieza tu historia?",
  "play.start.hint": "Elige por dónde entrar en este mundo. Tú decides quién eres.",
  "play.start.choose": "Empezar aquí",
  "play.start.chosen": "Seleccionado",
  "play.start.change": "Cambiar el inicio",
  "play.start.loreOnly": "Solo lore, no jugable",
  "play.start.selected": "La campaña empieza aquí.",
  "play.start.titleAttribute": "{{name}}: {{summary}}",
  "play.start.aria.group": "Inicios de la campaña",
  "play.start.aria.open": "Elige cómo empieza esta campaña",
  "play.start.aria.close": "Cerrar el selector de inicios",

  "play.error.loadTitle": "No consigo cargar esta campaña.",
  "play.error.loadFailed": "No he podido cargar esta campaña.",
  "play.error.loadPartial": "No he podido cargarlo todo.",
  "play.error.stale":
    "El narrador no terminó el turno: el backend se detuvo o se reinició mientras escribía y la respuesta nunca llegó.",
  "play.error.turnFailed": "El turno falló.",
  "play.error.turnUnfinished": "El turno se quedó a medias y nadie lo está escribiendo.",
  "play.error.turnNotFinished": "El narrador no terminó este turno.",
  "play.error.neverReached": "Nunca llegó al narrador.",

  "play.confirm.reset":
    "¿Empezar de nuevo la conversación? El prólogo del mundo se queda, los mensajes se van y el reparto de esta partida se borra. El canon, las épocas, la Biblia, los arcos y los capítulos no se tocan.",
  "play.confirm.removeCharacter": "¿Quitar {{name}} del mundo?",

  "play.adapt.castTitle": "Personajes del reparto",
  "play.adapt.castEmpty": "Ningún personaje canónico. Aparecen cuando tú los promueves.",
  "play.adapt.placesTitle": "Lugares",
  "play.adapt.placesEmpty": "Ningún lugar canónico.",
  "play.adapt.remove": "quita",
  "play.adapt.removeLabel": "Quitar {{name}}",
  "play.adapt.removeTitle": "Quitar del mundo",

  "play.history.chapters": "Capítulos",
  "play.history.openNotebook": "abre el cuaderno del mundo",

  "play.locale.chip": "idioma",

  "play.aria.backHome": "Volver al inicio",
};

export const playFr = {
  "play.tabs.overview": "Aperçu",
  "play.tabs.history": "Historique",
  "play.tabs.adaptation": "Adaptation",

  "play.turn.narrator": "narrateur",
  "play.turn.typing": "le narrateur est en train d'écrire",
  "play.turn.disclaimer": "Tout le contenu d'ici est généré par une IA et est purement fictif.",
  "play.turn.failedOne": "Un tour ne s'est pas bien terminé.",
  "play.turn.failedMany": "{{count}} tours ne se sont pas bien terminés.",
  "play.turn.failedWhy":
    "Ils sont là parce que ce que tu as écrit ne doit pas se perdre, et que l'historique seul ne raconte pas ce qui a mal tourné.",

  "play.action.send": "✨ Envoyer",
  "play.action.continue": "✨ Continuer",
  "play.action.retry": "↻ Réessayer",
  "play.action.delete": "⌫ Supprimer",
  "play.action.reset": "⟲ Recommencer",
  "play.action.discard": "jette",

  "play.composer.placeholder": "Parle, décris ce que tu fais ou ce qui se passe ensuite.",
  "play.composer.writing": "écrit…",
  "play.composer.locationUnset": "Lieu non déclaré",
  "play.composer.locationTitle":
    "Aide le narrateur à savoir qui est présent et quel canon s'applique ici. Il ne l'écrit pas tout seul : un lieu ne devient canon que si tu le déclares.",
  "play.composer.continueTitle":
    "Le narrateur poursuit. Ce n'est pas ton action, cela ne se termine donc pas dans la discussion.",
  "play.composer.retryIdleTitle": "Actif seulement si la dernière instruction a échoué",
  "play.composer.retryTitle": "Réessaie la dernière instruction",
  "play.composer.redoTitle":
    "Le narrateur raconte à nouveau la dernière scène, autrement. Mêmes circonstances, même canon, issue différente.",
  "play.composer.deleteTitle": "Supprime un seul message : seulement le dernier",
  "play.composer.resetTitle":
    "Ouvre une nouvelle conversation. Le canon, les personnages et les chapitres restent ; la discussion repart du prologue.",

  "play.settings.title": "Réglages",
  "play.settings.freeBadge": "Gratuit",
  "play.settings.writingHint":
    "Le narrateur écrit : le nouveau modèle s'applique à partir du prochain tour.",
  "play.settings.canonSummary": "Canon dans le contexte",
  "play.settings.arcMemory": "Mémoire des arcs",
  "play.settings.chat": "Réglages de la discussion",

  "play.context.estimated": "Contexte estimé",
  "play.context.limit": "limite {{limit}}",
  "play.context.tokens": "{{count}} tokens",
  "play.context.chapterAt": "chapitre à {{limit}}",
  "play.context.canonEntries": "{{entries}} entrées · {{tokens}} tokens",
  "play.context.canonOverBudget":
    "les niveaux obligatoires dépassent le budget : il faut un modèle avec plus de contexte",
  "play.context.arcTokens": "{{with}} tokens au lieu de {{without}}",
  "play.context.arcSaved": " · économie de {{percent}}%",
  "play.context.placeFree":
    "Le lieu est celui que tu dis dans le texte. En en choisissant un ici, le narrateur sait qui est présent et quel canon s'applique, mais cela ne devient pas canon : c'est toi qui décides.",
  "play.context.placeChosen": "Le narrateur croira que tu es à {{place}}.",
  "play.context.placeUnknown": "ce lieu",
  "play.context.newNames":
    "Le narrateur a cité des noms que le canon ne contient pas. Rien n'entre dans la base de données pendant la partie : c'est toi qui décides.",

  "play.state.worldFallback": "Le monde",
  "play.state.emptyHint":
    "Écris ce que tu veux qu'il arrive. Le narrateur répond à l'intérieur du monde et ne fera jamais rien que le canon n'autorise.",
  "play.state.noDescription": "Aucune description.",
  "play.state.noChapter": "aucun pour l'instant",
  "play.state.noTier": "aucun niveau",

  "play.start.title": "Comment votre histoire commence-t-elle ?",
  "play.start.hint": "Choisissez par où entrer dans ce monde. Vous décidez qui vous êtes.",
  "play.start.choose": "Commencer ici",
  "play.start.chosen": "Sélectionné",
  "play.start.change": "Changer de début",
  "play.start.loreOnly": "lore seule, non jouable",
  "play.start.selected": "La campagne commence ici.",
  "play.start.titleAttribute": "{{name}} : {{summary}}",
  "play.start.aria.group": "Débuts de campagne",
  "play.start.aria.open": "Choisir le début de cette campagne",
  "play.start.aria.close": "Fermer le sélecteur de début",

  "play.error.loadTitle": "Je n'arrive pas à charger cette campagne.",
  "play.error.loadFailed": "Je n'ai pas pu charger cette campagne.",
  "play.error.loadPartial": "Je n'ai pas pu tout charger.",
  "play.error.stale":
    "Le narrateur n'a pas terminé le tour : le backend s'est arrêté ou a redémarré pendant qu'il écrivait, et la réponse n'est jamais arrivée.",
  "play.error.turnFailed": "Le tour a échoué.",
  "play.error.turnUnfinished": "Le tour est resté à mi-chemin et personne ne l'écrit.",
  "play.error.turnNotFinished": "Le narrateur n'a pas terminé ce tour.",
  "play.error.neverReached": "Cela n'est jamais arrivé au narrateur.",

  "play.confirm.reset":
    "Recommencer la conversation ? Le prologue du monde reste, les messages disparaissent et le casting de cette partie est supprimé. Le canon, les ères, la Bible, les arcs et les chapitres ne sont pas touchés.",
  "play.confirm.removeCharacter": "Retirer {{name}} du monde ?",

  "play.adapt.castTitle": "Personnages du casting",
  "play.adapt.castEmpty": "Aucun personnage canon. Ils apparaissent quand tu les promeus.",
  "play.adapt.placesTitle": "Lieux",
  "play.adapt.placesEmpty": "Aucun lieu canon.",
  "play.adapt.remove": "retire",
  "play.adapt.removeLabel": "Retirer {{name}}",
  "play.adapt.removeTitle": "Retirer du monde",

  "play.history.chapters": "Chapitres",
  "play.history.openNotebook": "ouvre le carnet du monde",

  "play.locale.chip": "langue",

  "play.aria.backHome": "Retour à l'accueil",
};

export const playDe = {
  "play.tabs.overview": "Übersicht",
  "play.tabs.history": "Verlauf",
  "play.tabs.adaptation": "Anpassung",

  "play.turn.narrator": "Erzähler",
  "play.turn.typing": "der Erzähler schreibt gerade",
  "play.turn.disclaimer": "Der gesamte Inhalt hier wird von einer KI erzeugt und ist rein fiktiv.",
  "play.turn.failedOne": "Ein Zug ist nicht gut ausgegangen.",
  "play.turn.failedMany": "{{count}} Züge sind nicht gut ausgegangen.",
  "play.turn.failedWhy":
    "Sie stehen hier, damit das, was du geschrieben hast, nicht verloren geht, und die Chronologie allein nicht erzählt, was schiefgelaufen ist.",

  "play.action.send": "✨ Senden",
  "play.action.continue": "✨ Weiter",
  "play.action.retry": "↻ Erneut",
  "play.action.delete": "⌫ Löschen",
  "play.action.reset": "⟲ Neu beginnen",
  "play.action.discard": "weg damit",

  "play.composer.placeholder": "Sprich, beschreibe, was du tust oder was danach geschieht.",
  "play.composer.writing": "schreibt…",
  "play.composer.locationUnset": "Nicht genannter Ort",
  "play.composer.locationTitle":
    "Hilft dem Erzähler zu wissen, wer anwesend ist und welcher Kanon hier gilt. Er schreibt ihn nicht von selbst: ein Ort wird erst dann Kanon, wenn du ihn erklärst.",
  "play.composer.continueTitle":
    "Der Erzähler macht weiter. Das ist keine deiner Aktionen, deshalb landet es nicht im Chat.",
  "play.composer.retryIdleTitle": "Nur aktiv, wenn die letzte Eingabe fehlgeschlagen ist",
  "play.composer.retryTitle": "Versucht die letzte Eingabe erneut",
  "play.composer.redoTitle":
    "Der Erzähler erzählt die letzte Szene noch einmal, anders. Gleiche Umstände, gleicher Canon, anderes Ergebnis.",
  "play.composer.deleteTitle": "Löscht nur eine Nachricht: die letzte",
  "play.composer.resetTitle":
    "Öffnet eine neue Unterhaltung. Kanon, Figuren und Kapitel bleiben; der Chat beginnt wieder beim Prolog.",

  "play.settings.title": "Einstellungen",
  "play.settings.freeBadge": "Kostenlos",
  "play.settings.writingHint": "Der Erzähler schreibt: das neue Modell gilt ab dem nächsten Zug.",
  "play.settings.canonSummary": "Kanon im Kontext",
  "play.settings.arcMemory": "Erinnerung der Bögen",
  "play.settings.chat": "Chat-Einstellungen",

  "play.context.estimated": "Geschätzter Kontext",
  "play.context.limit": "Limit {{limit}}",
  "play.context.tokens": "{{count}} Token",
  "play.context.chapterAt": "Kapitel bei {{limit}}",
  "play.context.canonEntries": "{{entries}} Einträge · {{tokens}} Token",
  "play.context.canonOverBudget":
    "die Pflicht-Tiers überschreiten das Budget: ein Modell mit mehr Kontext wird gebraucht",
  "play.context.arcTokens": "{{with}} Token statt {{without}}",
  "play.context.arcSaved": " · Ersparnis {{percent}}%",
  "play.context.placeFree":
    "Der Ort ist der, den du im Text nennst. Wählst du hier einen aus, weiß der Erzähler, wer anwesend ist und welcher Kanon gilt, aber er macht ihn nicht zum Kanon: das entscheidest du.",
  "play.context.placeChosen": "Der Erzähler wird glauben, dass du in {{place}} bist.",
  "play.context.placeUnknown": "jenem Ort",
  "play.context.newNames":
    "Der Erzähler hat Namen genannt, die der Kanon nicht enthält. Im Spiel landet nichts in der Datenbank: du entscheidest.",

  "play.state.worldFallback": "Die Welt",
  "play.state.emptyHint":
    "Schreibe, was geschehen soll. Der Erzähler antwortet innerhalb der Welt und tut nie etwas, was der Kanon nicht erlaubt.",
  "play.state.noDescription": "Keine Beschreibung.",
  "play.state.noChapter": "noch keiner",
  "play.state.noTier": "kein Tier",

  "play.start.title": "Wie beginnt deine Geschichte?",
  "play.start.hint": "Wähle, wo du in diese Welt eintrittst. Du entscheidest, wer du bist.",
  "play.start.choose": "Hier beginnen",
  "play.start.chosen": "Ausgewählt",
  "play.start.change": "Start ändern",
  "play.start.loreOnly": "Nur Lore, nicht spielbar",
  "play.start.selected": "Die Kampagne beginnt hier.",
  "play.start.titleAttribute": "{{name}}: {{summary}}",
  "play.start.aria.group": "Kampagnen-Starts",
  "play.start.aria.open": "Wähle, wie diese Kampagne beginnt",
  "play.start.aria.close": "Start-Auswahl schließen",

  "play.error.loadTitle": "Ich kann diese Kampagne nicht laden.",
  "play.error.loadFailed": "Ich konnte diese Kampagne nicht laden.",
  "play.error.loadPartial": "Ich konnte nicht alles laden.",
  "play.error.stale":
    "Der Erzähler hat den Zug nicht beendet: Das Backend ist während des Schreibens stehen geblieben oder neu gestartet, und die Antwort ist nie angekommen.",
  "play.error.turnFailed": "Der Zug ist fehlgeschlagen.",
  "play.error.turnUnfinished": "Der Zug ist halbfertig geblieben und niemand schreibt daran.",
  "play.error.turnNotFinished": "Der Erzähler hat diesen Zug nicht beendet.",
  "play.error.neverReached": "Es ist nie beim Erzähler angekommen.",

  "play.confirm.reset":
    "Die Unterhaltung neu beginnen? Der Prolog der Welt bleibt, die Nachrichten gehen weg und die Besetzung dieses Durchlaufs wird gelöscht. Kanon, Epochen, Bibel, Bögen und Kapitel bleiben unberührt.",
  "play.confirm.removeCharacter": "{{name}} aus der Welt entfernen?",

  "play.adapt.castTitle": "Figuren des Castings",
  "play.adapt.castEmpty": "Keine Kanonsfigur. Sie erscheinen, wenn du sie beförderst.",
  "play.adapt.placesTitle": "Orte",
  "play.adapt.placesEmpty": "Kein kanonischer Ort.",
  "play.adapt.remove": "entfernen",
  "play.adapt.removeLabel": "{{name}} entfernen",
  "play.adapt.removeTitle": "Aus der Welt entfernen",

  "play.history.chapters": "Kapitel",
  "play.history.openNotebook": "Weltnotizbuch öffnen",

  "play.locale.chip": "Sprache",

  "play.aria.backHome": "Zurück zur Startseite",
};
